version: '3'

services:
  chastilock-backend:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: chastilock-backend
    container_name: chastilock-backend
    restart: unless-stopped
    environment:
      - DATABASE=mysql://mysql_user:mysql_password@db/chastilock
      - JWT_SECRET=secret
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - chastilock-network
  db:
    image: mysql:8
    container_name: chastilock-backend-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=chastilock
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_ROOT_PASSWORD=mysql_root_password
    ports:
      - "13306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - chastilock-network

networks:
  chastilock-network:
    external: true

volumes:
  dbdata:
  node_modules: